# Generated by Django 4.0.3 on 2022-04-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_remove_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='number',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Номер картинки'),
        ),
    ]
