# Generated by Django 4.0.3 on 2022-04-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_image_options_alter_place_description_long'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='PlaceImage',
        ),
    ]
